#!/usr/bin/env python3
"""Builds the seed datasets: regulations.json and controls.json.
Run:  python scripts/build_seed.py
Covers medical device, manufacturing, and IT/OT regulations worldwide
(existing + emerging). URLs point at official/canonical sources and should
be re-verified periodically by the weekly crawler.
"""
import json, os, hashlib

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "backend", "app", "data")
os.makedirs(OUT, exist_ok=True)

# --------------------------------------------------------------------------
# REGULATIONS
# domain: device | manufacturing | itot | privacy | ai | crosscutting
# applies_when criteria (OR within a list, AND across present keys):
#   markets, product_types, data_types, flags
# --------------------------------------------------------------------------
REGS = [
 # ---------------- US medical device ----------------
 dict(id="FDA-510K", name="FDA 510(k) Premarket Notification", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="premarket",
   url="https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/premarket-notification-510k",
   summary="Premarket notification demonstrating that a Class II device is substantially equivalent to a legally marketed predicate device before it may be marketed in the US.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["medical_device","samd"]),
   topics=["submission","predicate","classification"]),
 dict(id="FDA-QMSR", name="FDA QMSR / 21 CFR Part 820", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="qms",
   url="https://www.ecfr.gov/current/title-21/chapter-I/subchapter-H/part-820",
   summary="FDA quality system requirements for medical device design, manufacture and servicing. The 2024 QMSR final rule harmonises Part 820 with ISO 13485 (in force Feb 2026).",
   emerging=True, applies_when=dict(markets=["United States"], product_types=["medical_device","samd"]),
   topics=["qms","design controls","capa"]),
 dict(id="FDA-21CFR11", name="21 CFR Part 11 — Electronic Records", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="records",
   url="https://www.ecfr.gov/current/title-21/chapter-I/subchapter-A/part-11",
   summary="Requirements for trustworthy electronic records and electronic signatures used in FDA-regulated activities, including audit trails, validation and access controls.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["software"]),
   topics=["records","signatures","validation"]),
 dict(id="FDA-CYBER", name="FDA Premarket Cybersecurity (Section 524B)", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://www.fda.gov/medical-devices/digital-health-center-excellence/cybersecurity",
   summary="Mandatory cybersecurity requirements for 'cyber devices' under FD&C Act 524B: SBOM, coordinated vulnerability disclosure, secure design and post-market patching.",
   emerging=True, applies_when=dict(markets=["United States"], product_types=["medical_device","samd"], flags=["connected","software"]),
   topics=["cybersecurity","sbom","cvd"]),
 dict(id="HIPAA", name="HIPAA Security & Privacy Rules", body="US HHS", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://www.hhs.gov/hipaa/for-professionals/security/index.html",
   summary="US federal safeguards (administrative, physical, technical) for electronic protected health information, plus breach notification within 60 days. A 2025 NPRM proposes making several addressable safeguards mandatory.",
   emerging=True, applies_when=dict(markets=["United States"], data_types=["phi"]),
   topics=["ephi","safeguards","breach"]),
 dict(id="FDA-UDI", name="FDA UDI — Unique Device Identification", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="labelling",
   url="https://www.fda.gov/medical-devices/device-advice-comprehensive-regulatory-assistance/unique-device-identification-system-udi-system",
   summary="Device labelling with a unique device identifier and submission to the GUDID database, phased by device class.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["medical_device"]),
   topics=["udi","gudid","labelling"]),

 # ---------------- EU medical device / privacy / AI ----------------
 dict(id="EU-MDR", name="EU MDR 2017/745", body="European Union", domain="device",
   region="EU", jurisdictions=["EU","EEA"], category="premarket",
   url="https://eur-lex.europa.eu/eli/reg/2017/745/oj",
   summary="EU medical device regulation governing CE marking: technical documentation, clinical evaluation, post-market surveillance, PMCF and Notified Body involvement for Class IIa and above.",
   emerging=False, applies_when=dict(markets=["EU","EEA"], product_types=["medical_device"]),
   topics=["ce mark","clinical","pmcf","udi"]),
 dict(id="EU-IVDR", name="EU IVDR 2017/746", body="European Union", domain="device",
   region="EU", jurisdictions=["EU","EEA"], category="premarket",
   url="https://eur-lex.europa.eu/eli/reg/2017/746/oj",
   summary="EU in-vitro diagnostic regulation; reclassifies most IVDs and expands Notified Body and performance-evaluation requirements.",
   emerging=False, applies_when=dict(markets=["EU","EEA"], product_types=["ivd"]),
   topics=["ivd","ce mark","performance"]),
 dict(id="EU-GDPR", name="EU GDPR 2016/679", body="European Union", domain="privacy",
   region="EU", jurisdictions=["EU","EEA"], category="privacy",
   url="https://eur-lex.europa.eu/eli/reg/2016/679/oj",
   summary="Protection of personal and special-category (health) data: lawful basis, data-subject rights, Article 32 security of processing, Article 33 72-hour breach notice, Article 28 processor contracts.",
   emerging=False, applies_when=dict(markets=["EU","EEA"], data_types=["eu_personal","pii"]),
   topics=["privacy","data subject rights","transfers"]),
 dict(id="EU-AI-ACT", name="EU AI Act — Regulation 2024/1689", body="European Union", domain="ai",
   region="EU", jurisdictions=["EU"], category="ai",
   url="https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
   summary="Risk-based regulation of AI systems. AI that is a safety component of a medical device is high-risk: risk management, data governance, transparency, human oversight and conformity assessment, phasing in from 2025-2027.",
   emerging=True, applies_when=dict(markets=["EU"], flags=["ai"]),
   topics=["ai","high-risk","transparency"]),
 dict(id="EU-CRA", name="EU Cyber Resilience Act 2024/2847", body="European Union", domain="itot",
   region="EU", jurisdictions=["EU"], category="cybersecurity",
   url="https://eur-lex.europa.eu/eli/reg/2024/2847/oj",
   summary="Horizontal cybersecurity requirements for products with digital elements placed on the EU market: secure-by-design, vulnerability handling, SBOM and reporting of actively exploited vulnerabilities. Main obligations apply from 2027.",
   emerging=True, applies_when=dict(markets=["EU"], flags=["software","connected"]),
   topics=["cybersecurity","secure-by-design","sbom"]),
 dict(id="EU-NIS2", name="EU NIS2 Directive 2022/2555", body="European Union", domain="itot",
   region="EU", jurisdictions=["EU"], category="cybersecurity",
   url="https://eur-lex.europa.eu/eli/dir/2022/2555/oj",
   summary="Cybersecurity risk-management and incident-reporting obligations for essential and important entities, including parts of healthcare and manufacturing supply chains, with management accountability.",
   emerging=True, applies_when=dict(markets=["EU"], flags=["ot","manufactures","connected"]),
   topics=["nis2","incident reporting","supply chain"]),
 dict(id="MDCG-CYBER", name="MDCG 2019-16 — Cybersecurity for MDR/IVDR", body="EU MDCG", domain="device",
   region="EU", jurisdictions=["EU"], category="cybersecurity",
   url="https://health.ec.europa.eu/medical-devices-sector/new-regulations/guidance-mdcg-endorsed-documents-and-other-guidance_en",
   summary="EU guidance on addressing cybersecurity within MDR/IVDR technical documentation: security risk management, secure design, network and data protection, and vulnerability handling.",
   emerging=False, applies_when=dict(markets=["EU","EEA"], product_types=["medical_device","samd"], flags=["connected","software"]),
   topics=["cybersecurity","mdr","technical documentation"]),

 # ---------------- UK / APAC / Americas device ----------------
 dict(id="UK-MDR", name="UK MDR 2002 / UKCA", body="UK MHRA", domain="device",
   region="UK", jurisdictions=["United Kingdom"], category="premarket",
   url="https://www.gov.uk/government/collections/medical-devices-regulation-and-safety",
   summary="UK medical device framework; UKCA marking for Great Britain, MHRA registration, a UK Responsible Person for overseas manufacturers and new post-market surveillance regulations.",
   emerging=True, applies_when=dict(markets=["United Kingdom"], product_types=["medical_device"]),
   topics=["ukca","mhra","pms"]),
 dict(id="PMDA-JP", name="Japan PMD Act (PMDA)", body="Japan PMDA", domain="device",
   region="APAC", jurisdictions=["Japan"], category="premarket",
   url="https://www.pmda.go.jp/english/",
   summary="Japanese marketing authorisation for medical devices: QMS conformity, Japanese clinical data where required, and a Designated Marketing Authorisation Holder.",
   emerging=False, applies_when=dict(markets=["Japan"], product_types=["medical_device"]),
   topics=["pmda","dmah","qms"]),
 dict(id="NMPA-CN", name="China NMPA Medical Device Regulations", body="China NMPA", domain="device",
   region="APAC", jurisdictions=["China"], category="premarket",
   url="https://www.nmpa.gov.cn/",
   summary="China registration for medical devices: clinical evaluation, China-specific testing and labelling, and a local legal agent.",
   emerging=False, applies_when=dict(markets=["China"], product_types=["medical_device"]),
   topics=["nmpa","registration","clinical"]),
 dict(id="TGA-AU", name="Australia TGA Medical Devices", body="Australia TGA", domain="device",
   region="APAC", jurisdictions=["Australia"], category="premarket",
   url="https://www.tga.gov.au/products/medical-devices",
   summary="Australian device approvals: ARTG inclusion, conformity assessment and mandatory adverse-event reporting.",
   emerging=False, applies_when=dict(markets=["Australia"], product_types=["medical_device"]),
   topics=["tga","artg","conformity"]),
 dict(id="HC-CA", name="Health Canada Medical Device Regulations", body="Health Canada", domain="device",
   region="Americas", jurisdictions=["Canada"], category="premarket",
   url="https://www.canada.ca/en/health-canada/services/drugs-health-products/medical-devices.html",
   summary="Canadian device licensing; Class II-IV require a Medical Device Licence and ISO 13485 certification under MDSAP.",
   emerging=False, applies_when=dict(markets=["Canada"], product_types=["medical_device"]),
   topics=["licence","mdsap","qms"]),
 dict(id="MDSAP", name="MDSAP — Medical Device Single Audit Program", body="IMDRF/Regulators", domain="device",
   region="Global", jurisdictions=["United States","Canada","Australia","Brazil","Japan"], category="qms",
   url="https://www.fda.gov/medical-devices/cdrh-international-programs/medical-device-single-audit-program-mdsap",
   summary="A single regulatory audit of a manufacturer's QMS accepted by the US, Canada, Australia, Brazil and Japan.",
   emerging=False, applies_when=dict(product_types=["medical_device"], markets=["Canada","Australia","Brazil","Japan"]),
   topics=["audit","qms","multi-market"]),

 # ---------------- International standards (device + software + risk) ----------------
 dict(id="ISO-13485", name="ISO 13485:2016 — Medical Device QMS", body="ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="qms",
   url="https://www.iso.org/standard/59752.html",
   summary="International quality management system standard for the design, production and servicing of medical devices; the de-facto basis for most market approvals.",
   emerging=False, applies_when=dict(product_types=["medical_device","samd","ivd"]),
   topics=["qms","certification"]),
 dict(id="ISO-14971", name="ISO 14971:2019 — Risk Management", body="ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="risk",
   url="https://www.iso.org/standard/72704.html",
   summary="Application of risk management across the medical device lifecycle: risk analysis, evaluation, control and residual-risk acceptance.",
   emerging=False, applies_when=dict(product_types=["medical_device","samd","ivd"]),
   topics=["risk","safety"]),
 dict(id="IEC-62304", name="IEC 62304 — Medical Device Software Lifecycle", body="IEC", domain="device",
   region="Global", jurisdictions=["Global"], category="software",
   url="https://webstore.iec.ch/publication/22794",
   summary="Software lifecycle processes for medical device software, with Class A/B/C safety classification; referenced by FDA and EU MDR.",
   emerging=False, applies_when=dict(product_types=["samd","medical_device"], flags=["software"]),
   topics=["software","lifecycle","soup"]),
 dict(id="IEC-60601", name="IEC 60601 — Medical Electrical Equipment Safety", body="IEC", domain="device",
   region="Global", jurisdictions=["Global"], category="safety",
   url="https://webstore.iec.ch/publication/2612",
   summary="Basic safety and essential performance for medical electrical equipment, including EMC and usability collaterals.",
   emerging=False, applies_when=dict(product_types=["medical_device"]),
   topics=["electrical safety","emc","hardware"]),
 dict(id="IEC-62366", name="IEC 62366-1 — Usability Engineering", body="IEC", domain="device",
   region="Global", jurisdictions=["Global"], category="usability",
   url="https://webstore.iec.ch/publication/63179",
   summary="Application of usability (human factors) engineering to medical devices to reduce use-related risk.",
   emerging=False, applies_when=dict(product_types=["medical_device","samd"]),
   topics=["usability","human factors"]),
 dict(id="ISO-27001", name="ISO/IEC 27001:2022 — Information Security", body="ISO/IEC", domain="itot",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://www.iso.org/standard/27001",
   summary="Requirements for an information security management system (ISMS) with Annex A controls; the common baseline that underpins most security regimes.",
   emerging=False, applies_when=dict(flags=["software","connected"]),
   topics=["isms","security","certification"]),
 dict(id="ISO-42001", name="ISO/IEC 42001:2023 — AI Management System", body="ISO/IEC", domain="ai",
   region="Global", jurisdictions=["Global"], category="ai",
   url="https://www.iso.org/standard/81230.html",
   summary="Management system standard for responsible development and use of AI, complementary to the EU AI Act and FDA AI guidance.",
   emerging=True, applies_when=dict(flags=["ai"]),
   topics=["ai","governance","management system"]),
 dict(id="IMDRF-CYBER", name="IMDRF Principles & Practices for Device Cybersecurity", body="IMDRF", domain="device",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://www.imdrf.org/documents",
   summary="Internationally harmonised medical device cybersecurity guidance that underpins FDA, EU and APAC requirements across the total product lifecycle.",
   emerging=False, applies_when=dict(product_types=["medical_device","samd"], flags=["connected","software"]),
   topics=["cybersecurity","harmonisation","tplc"]),

 # ---------------- Manufacturing ----------------
 dict(id="ISO-9001", name="ISO 9001:2015 — Quality Management", body="ISO", domain="manufacturing",
   region="Global", jurisdictions=["Global"], category="qms",
   url="https://www.iso.org/standard/62085.html",
   summary="General quality management system standard for consistent products and continual improvement across manufacturing organisations.",
   emerging=False, applies_when=dict(flags=["manufactures"]),
   topics=["qms","manufacturing","improvement"]),
 dict(id="OSHA", name="US OSHA Workplace Safety", body="US DOL OSHA", domain="manufacturing",
   region="US", jurisdictions=["United States"], category="safety",
   url="https://www.osha.gov/laws-regs",
   summary="US occupational safety and health requirements for manufacturing workplaces, including hazard communication, machine guarding and process safety management.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["manufactures"]),
   topics=["worker safety","psm","hazard"]),
 dict(id="ISO-45001", name="ISO 45001:2018 — Occupational Health & Safety", body="ISO", domain="manufacturing",
   region="Global", jurisdictions=["Global"], category="safety",
   url="https://www.iso.org/standard/63787.html",
   summary="Management system for occupational health and safety to prevent work-related injury and ill-health in manufacturing operations.",
   emerging=False, applies_when=dict(flags=["manufactures"]),
   topics=["ohs","worker safety"]),
 dict(id="ISO-14001", name="ISO 14001:2015 — Environmental Management", body="ISO", domain="manufacturing",
   region="Global", jurisdictions=["Global"], category="environment",
   url="https://www.iso.org/standard/60857.html",
   summary="Environmental management system standard for controlling environmental impact and meeting compliance obligations in manufacturing.",
   emerging=False, applies_when=dict(flags=["manufactures"]),
   topics=["environment","ems"]),

 # ---------------- IT / OT / ICS cybersecurity ----------------
 dict(id="IEC-62443", name="IEC 62443 — Industrial Automation & Control Systems Security", body="IEC/ISA", domain="itot",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://www.isa.org/standards-and-publications/isa-standards/isa-iec-62443-series-of-standards",
   summary="Series of standards for the cybersecurity of industrial automation and control systems (OT), defining security levels, zones and conduits, and a secure development lifecycle.",
   emerging=False, applies_when=dict(flags=["ot"]),
   topics=["ics","ot","security levels"]),
 dict(id="NIST-80082", name="NIST SP 800-82 Rev 3 — OT Security", body="US NIST", domain="itot",
   region="US", jurisdictions=["United States","Global"], category="cybersecurity",
   url="https://csrc.nist.gov/pubs/sp/800/82/r3/final",
   summary="Guide to operational technology (OT) security covering ICS, SCADA and DCS risk management, architecture and controls.",
   emerging=False, applies_when=dict(flags=["ot"]),
   topics=["ot","ics","scada"]),
 dict(id="NIST-CSF", name="NIST Cybersecurity Framework 2.0", body="US NIST", domain="itot",
   region="US", jurisdictions=["United States","Global"], category="cybersecurity",
   url="https://www.nist.gov/cyberframework",
   summary="Voluntary framework organising cybersecurity outcomes across Govern, Identify, Protect, Detect, Respond and Recover; widely used to crosswalk other regimes.",
   emerging=False, applies_when=dict(flags=["software","connected","ot"]),
   topics=["csf","govern","crosswalk"]),
 dict(id="NIST-80053", name="NIST SP 800-53 Rev 5 — Security & Privacy Controls", body="US NIST", domain="itot",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
   summary="Catalogue of security and privacy controls for information systems, used as a control baseline and for FedRAMP/government contexts.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["software"]),
   topics=["controls","baseline","privacy"]),
 dict(id="SOC2", name="AICPA SOC 2 (Trust Services Criteria)", body="AICPA", domain="saas",
   region="US", jurisdictions=["United States"], category="assurance",
   url="https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
   summary="Independent attestation of security, availability, confidentiality, processing integrity and privacy controls; Type II tests operating effectiveness over a period.",
   emerging=False, applies_when=dict(flags=["software","connected"], product_types=["healthcare_saas","samd","saas","fintech","edtech","consumer"]),
   topics=["soc2","tsc","assurance"]),
 dict(id="PCI-DSS", name="PCI DSS v4.0.1", body="PCI SSC", domain="itot",
   region="Global", jurisdictions=["Global"], category="payments",
   url="https://www.pcisecuritystandards.org/standards/",
   summary="Security standard for systems that store, process or transmit payment card data; v4.0 requirements (e.g. MFA everywhere, targeted risk analyses) became mandatory in 2025.",
   emerging=False, applies_when=dict(data_types=["payment"]),
   topics=["payments","cardholder data"]),

 # ===================== additional global coverage =====================
 # ---- Device market approvals (more countries) ----
 dict(id="ANVISA-BR", name="Brazil ANVISA (RDC 751/2022)", body="Brazil ANVISA", domain="device",
   region="Americas", jurisdictions=["Brazil"], category="premarket",
   url="https://www.gov.br/anvisa/pt-br",
   summary="Brazilian medical device registration and Good Manufacturing Practice certification; risk classes I-IV with INMETRO certification for some devices.",
   emerging=False, applies_when=dict(markets=["Brazil"], product_types=["medical_device","ivd"]),
   topics=["registration","bgmp"]),
 dict(id="MFDS-KR", name="South Korea MFDS Medical Devices", body="Korea MFDS", domain="device",
   region="APAC", jurisdictions=["South Korea"], category="premarket",
   url="https://www.mfds.go.kr/eng/index.do",
   summary="Korean medical device approval: KGMP, technical documentation and clinical data where required, with a Korea License Holder.",
   emerging=False, applies_when=dict(markets=["South Korea"], product_types=["medical_device","ivd"]),
   topics=["kgmp","registration"]),
 dict(id="CDSCO-IN", name="India CDSCO (Medical Device Rules 2017)", body="India CDSCO", domain="device",
   region="APAC", jurisdictions=["India"], category="premarket",
   url="https://cdsco.gov.in/opencms/opencms/en/Home/",
   summary="Indian medical device licensing under the Medical Device Rules 2017, with risk-based classes A-D and an Indian authorised agent.",
   emerging=False, applies_when=dict(markets=["India"], product_types=["medical_device","ivd"]),
   topics=["licensing","mdr-2017"]),
 dict(id="HSA-SG", name="Singapore HSA Medical Devices", body="Singapore HSA", domain="device",
   region="APAC", jurisdictions=["Singapore"], category="premarket",
   url="https://www.hsa.gov.sg/medical-devices",
   summary="Singapore device registration on the medical device register with risk classification and a registrant established in Singapore.",
   emerging=False, applies_when=dict(markets=["Singapore"], product_types=["medical_device","ivd"]),
   topics=["registration","classification"]),
 dict(id="SWISSMEDIC-CH", name="Switzerland MedDO / Swissmedic", body="Swissmedic", domain="device",
   region="EU", jurisdictions=["Switzerland"], category="premarket",
   url="https://www.swissmedic.ch/swissmedic/en/home/medical-devices.html",
   summary="Swiss medical device ordinance (MedDO) broadly aligned with EU MDR; requires a Swiss authorised representative (CH-REP) and registration.",
   emerging=False, applies_when=dict(markets=["Switzerland"], product_types=["medical_device"]),
   topics=["meddo","ch-rep"]),

 # ---- US additional premarket / AI ----
 dict(id="FDA-PMA", name="FDA Premarket Approval (PMA)", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="premarket",
   url="https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/premarket-approval-pma",
   summary="The most stringent US pathway for high-risk (Class III) devices, requiring valid scientific evidence of safety and effectiveness.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["medical_device"]),
   topics=["class iii","clinical"]),
 dict(id="FDA-DENOVO", name="FDA De Novo Classification", body="US FDA", domain="device",
   region="US", jurisdictions=["United States"], category="premarket",
   url="https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/de-novo-classification-request",
   summary="US pathway for novel low/moderate-risk devices without a predicate, creating a new classification.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["medical_device","samd"]),
   topics=["novel","classification"]),
 dict(id="FDA-PCCP", name="FDA Predetermined Change Control Plan (AI/ML)", body="US FDA", domain="ai",
   region="US", jurisdictions=["United States"], category="ai",
   url="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence",
   summary="Lets manufacturers pre-specify and gain authorisation for future AI/ML model changes (a PCCP) without a new submission for each update.",
   emerging=True, applies_when=dict(markets=["United States"], flags=["ai"]),
   topics=["ai","change control","ml"]),
 dict(id="FDA-GMLP", name="Good Machine Learning Practice (GMLP)", body="FDA/MHRA/HC", domain="ai",
   region="Global", jurisdictions=["United States","United Kingdom","Canada"], category="ai",
   url="https://www.fda.gov/medical-devices/software-medical-device-samd/good-machine-learning-practice-medical-device-development-guiding-principles",
   summary="Jointly published guiding principles for the development of safe, effective machine-learning-enabled medical devices.",
   emerging=True, applies_when=dict(flags=["ai"], product_types=["samd","medical_device"]),
   topics=["ai","gmlp","ml"]),
 dict(id="US-CURES", name="US 21st Century Cures Act — Info Blocking (ONC)", body="US ONC", domain="itot",
   region="US", jurisdictions=["United States"], category="interoperability",
   url="https://www.healthit.gov/topic/oncs-cures-act-final-rule",
   summary="Prohibits information blocking and requires standardised API access (FHIR) to electronic health information for certified health IT.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["healthcare_saas"], flags=["software"]),
   topics=["interoperability","fhir","info blocking"]),

 # ---- Privacy laws across the globe ----
 dict(id="US-CCPA", name="California CCPA / CPRA", body="California AG / CPPA", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://oag.ca.gov/privacy/ccpa",
   summary="California consumer privacy rights (access, deletion, opt-out of sale/sharing) and business obligations, expanded by the CPRA.",
   emerging=False, applies_when=dict(markets=["United States"], data_types=["pii","phi"]),
   topics=["privacy","consumer rights"]),
 dict(id="CA-PIPEDA", name="Canada PIPEDA", body="Canada OPC", domain="privacy",
   region="Americas", jurisdictions=["Canada"], category="privacy",
   url="https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/",
   summary="Canadian federal private-sector privacy law governing collection, use and disclosure of personal information, with consent and breach reporting.",
   emerging=False, applies_when=dict(markets=["Canada"], data_types=["pii","phi"]),
   topics=["privacy","consent"]),
 dict(id="BR-LGPD", name="Brazil LGPD", body="Brazil ANPD", domain="privacy",
   region="Americas", jurisdictions=["Brazil"], category="privacy",
   url="https://www.gov.br/anpd/pt-br",
   summary="Brazilian general data protection law modelled on GDPR: legal bases, data-subject rights and breach notification, enforced by the ANPD.",
   emerging=False, applies_when=dict(markets=["Brazil"], data_types=["pii"]),
   topics=["privacy","lgpd"]),
 dict(id="CN-PIPL", name="China PIPL", body="China CAC", domain="privacy",
   region="APAC", jurisdictions=["China"], category="privacy",
   url="https://www.cac.gov.cn/",
   summary="China's Personal Information Protection Law: consent, data-localisation and strict cross-border transfer requirements for personal information.",
   emerging=True, applies_when=dict(markets=["China"], data_types=["pii","phi"]),
   topics=["privacy","cross-border"]),
 dict(id="JP-APPI", name="Japan APPI", body="Japan PPC", domain="privacy",
   region="APAC", jurisdictions=["Japan"], category="privacy",
   url="https://www.ppc.go.jp/en/",
   summary="Japan's Act on the Protection of Personal Information, with rules for handling and cross-border transfer of personal data.",
   emerging=False, applies_when=dict(markets=["Japan"], data_types=["pii","phi"]),
   topics=["privacy","appi"]),
 dict(id="UK-GDPR", name="UK GDPR & Data Protection Act 2018", body="UK ICO", domain="privacy",
   region="UK", jurisdictions=["United Kingdom"], category="privacy",
   url="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/",
   summary="The UK's data protection regime mirroring the EU GDPR, regulated by the ICO, covering personal and special-category health data.",
   emerging=False, applies_when=dict(markets=["United Kingdom"], data_types=["pii","eu_personal"]),
   topics=["privacy","uk gdpr"]),
 dict(id="SG-PDPA", name="Singapore PDPA", body="Singapore PDPC", domain="privacy",
   region="APAC", jurisdictions=["Singapore"], category="privacy",
   url="https://www.pdpc.gov.sg/",
   summary="Singapore's Personal Data Protection Act governing consent, purpose limitation, protection and breach notification.",
   emerging=False, applies_when=dict(markets=["Singapore"], data_types=["pii","phi"]),
   topics=["privacy","pdpa"]),
 dict(id="KR-PIPA", name="South Korea PIPA", body="Korea PIPC", domain="privacy",
   region="APAC", jurisdictions=["South Korea"], category="privacy",
   url="https://www.pipc.go.kr/eng/",
   summary="South Korea's Personal Information Protection Act, among the strictest globally, with consent and cross-border transfer controls.",
   emerging=False, applies_when=dict(markets=["South Korea"], data_types=["pii","phi"]),
   topics=["privacy","pipa"]),

 # ---- China / OT cyber ----
 dict(id="CN-CSL", name="China Cybersecurity Law & MLPS 2.0", body="China CAC", domain="itot",
   region="APAC", jurisdictions=["China"], category="cybersecurity",
   url="https://www.cac.gov.cn/",
   summary="China's cybersecurity law with the Multi-Level Protection Scheme (MLPS 2.0) grading and security obligations for network operators.",
   emerging=False, applies_when=dict(markets=["China"], flags=["software","connected"]),
   topics=["cybersecurity","mlps"]),
 dict(id="CN-DSL", name="China Data Security Law", body="China CAC", domain="itot",
   region="APAC", jurisdictions=["China"], category="cybersecurity",
   url="https://www.cac.gov.cn/",
   summary="Classifies and protects data by importance, with security obligations and restrictions on cross-border transfer of important data.",
   emerging=False, applies_when=dict(markets=["China"], data_types=["pii","phi"]),
   topics=["data security","cross-border"]),
 dict(id="NERC-CIP", name="NERC CIP — Critical Infrastructure (Energy OT)", body="NERC", domain="itot",
   region="Americas", jurisdictions=["United States","Canada"], category="cybersecurity",
   url="https://www.nerc.com/pa/Stand/Pages/CIPStandards.aspx",
   summary="Mandatory cybersecurity standards for the North American bulk electric system — relevant to OT vendors in the energy sector.",
   emerging=False, applies_when=dict(flags=["ot"], markets=["United States","Canada"]),
   topics=["ot","critical infrastructure"]),
 dict(id="IEC-61508", name="IEC 61508 — Functional Safety", body="IEC", domain="itot",
   region="Global", jurisdictions=["Global"], category="safety",
   url="https://www.iec.ch/functional-safety",
   summary="Functional safety of electrical/electronic/programmable safety-related systems (SIL), foundational for many OT and device safety functions.",
   emerging=False, applies_when=dict(flags=["ot","software"]),
   topics=["functional safety","sil"]),

 # ---- Security / privacy / AI standards ----
 dict(id="IEC-81001", name="IEC 81001-5-1 — Health Software Security", body="IEC/ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://webstore.iec.ch/publication/72260",
   summary="Security activities across the health software lifecycle; increasingly referenced by regulators alongside IEC 62304.",
   emerging=True, applies_when=dict(product_types=["samd","medical_device"], flags=["software"]),
   topics=["health software","security lifecycle"]),
 dict(id="ISO-27701", name="ISO/IEC 27701 — Privacy Information Management", body="ISO/IEC", domain="privacy",
   region="Global", jurisdictions=["Global"], category="privacy",
   url="https://www.iso.org/standard/71670.html",
   summary="Extension to ISO 27001 for a Privacy Information Management System (PIMS), mapping to GDPR and other privacy regimes.",
   emerging=False, applies_when=dict(data_types=["pii","eu_personal","phi"]),
   topics=["pims","privacy"]),
 dict(id="ISO-27017", name="ISO/IEC 27017 — Cloud Security", body="ISO/IEC", domain="itot",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://www.iso.org/standard/43757.html",
   summary="Cloud-specific information security controls for cloud service providers and customers.",
   emerging=False, applies_when=dict(flags=["software","connected"]),
   topics=["cloud","security"]),
 dict(id="ISO-27018", name="ISO/IEC 27018 — Cloud PII Protection", body="ISO/IEC", domain="privacy",
   region="Global", jurisdictions=["Global"], category="privacy",
   url="https://www.iso.org/standard/76559.html",
   summary="Code of practice for protecting personally identifiable information in public clouds acting as PII processors.",
   emerging=False, applies_when=dict(data_types=["pii","phi"], flags=["software"]),
   topics=["cloud","pii"]),
 dict(id="ISO-80001", name="IEC 80001-1 — Medical IT Network Risk", body="IEC/ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="cybersecurity",
   url="https://www.iso.org/standard/72026.html",
   summary="Risk management for IT networks incorporating medical devices, covering safety, effectiveness and security.",
   emerging=False, applies_when=dict(product_types=["medical_device"], flags=["connected"]),
   topics=["it network","risk"]),
 dict(id="AAMI-TIR57", name="AAMI TIR57 — Device Cybersecurity Risk", body="AAMI", domain="device",
   region="US", jurisdictions=["United States","Global"], category="cybersecurity",
   url="https://www.aami.org/standards",
   summary="Technical guidance on applying security risk management to medical devices, complementing ISO 14971 and FDA expectations.",
   emerging=False, applies_when=dict(product_types=["medical_device","samd"], flags=["connected","software"]),
   topics=["cybersecurity","risk"]),
 dict(id="UL-2900", name="UL 2900 — Cybersecurity Assurance", body="UL", domain="itot",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://www.shopulstandards.com/ProductDetail.aspx?productId=UL2900-1",
   summary="Testable cybersecurity requirements for network-connectable products, including medical devices (UL 2900-2-1).",
   emerging=False, applies_when=dict(flags=["connected","software"]),
   topics=["cybersecurity","testing"]),
 dict(id="NIST-80171", name="NIST SP 800-171 — Protect CUI", body="US NIST", domain="itot",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://csrc.nist.gov/pubs/sp/800/171/r3/final",
   summary="Controls to protect Controlled Unclassified Information in non-federal systems; required for many US government contracts.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["software"]),
   topics=["cui","government"]),
 dict(id="CMMC", name="CMMC 2.0 — US Defense Cybersecurity", body="US DoD", domain="itot",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://dodcio.defense.gov/cmmc/",
   summary="Cybersecurity Maturity Model Certification for the US defense industrial base, building on NIST SP 800-171.",
   emerging=True, applies_when=dict(markets=["United States"], flags=["defense","us_gov"]),
   topics=["cmmc","defense","cui","800-171"]),
 dict(id="HITRUST", name="HITRUST CSF", body="HITRUST", domain="itot",
   region="US", jurisdictions=["United States"], category="assurance",
   url="https://hitrustalliance.net/",
   summary="A certifiable security and privacy framework widely required by US healthcare partners, harmonising HIPAA, NIST and ISO.",
   emerging=False, applies_when=dict(data_types=["phi"], flags=["software"]),
   topics=["healthcare","assurance"]),
 dict(id="NIST-AI-RMF", name="NIST AI Risk Management Framework", body="US NIST", domain="ai",
   region="US", jurisdictions=["United States","Global"], category="ai",
   url="https://www.nist.gov/itl/ai-risk-management-framework",
   summary="Voluntary framework to govern, map, measure and manage AI risks; a practical companion to the EU AI Act and ISO 42001.",
   emerging=True, applies_when=dict(flags=["ai"]),
   topics=["ai","risk"]),
 dict(id="OECD-AI", name="OECD AI Principles", body="OECD", domain="ai",
   region="Global", jurisdictions=["Global"], category="ai",
   url="https://oecd.ai/en/ai-principles",
   summary="Intergovernmental principles for trustworthy AI (transparency, robustness, accountability) adopted by many jurisdictions.",
   emerging=False, applies_when=dict(flags=["ai"]),
   topics=["ai","principles"]),

 # ---- Device materials / sterilization / labelling ----
 dict(id="ISO-10993", name="ISO 10993 — Biological Evaluation", body="ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="safety",
   url="https://www.iso.org/standard/68936.html",
   summary="Biocompatibility evaluation of medical devices in contact with the body; required for materials safety in most markets.",
   emerging=False, applies_when=dict(product_types=["medical_device"]),
   topics=["biocompatibility","materials"]),
 dict(id="ISO-11135", name="ISO 11135 — EO Sterilization", body="ISO", domain="manufacturing",
   region="Global", jurisdictions=["Global"], category="safety",
   url="https://www.iso.org/standard/56137.html",
   summary="Validation and routine control of ethylene-oxide sterilization for medical devices.",
   emerging=False, applies_when=dict(product_types=["medical_device"], flags=["manufactures"]),
   topics=["sterilization","validation"]),
 dict(id="ISO-15223", name="ISO 15223-1 — Labelling Symbols", body="ISO", domain="device",
   region="Global", jurisdictions=["Global"], category="labelling",
   url="https://www.iso.org/standard/77326.html",
   summary="Standardised symbols for medical device labels, labelling and information to be supplied.",
   emerging=False, applies_when=dict(product_types=["medical_device","ivd"]),
   topics=["labelling","symbols"]),

 # ===================== SaaS / cloud / software products =====================
 dict(id="SOC1", name="SOC 1 / ISAE 3402 — Financial Controls", body="AICPA / IAASB", domain="saas",
   region="US", jurisdictions=["United States","Global"], category="assurance",
   url="https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-1",
   summary="Audit of controls at a service organisation that are relevant to user entities' internal control over financial reporting.",
   emerging=False, applies_when=dict(product_types=["saas","fintech"], data_types=["financial"]),
   topics=["financial controls","icfr","assurance"]),
 dict(id="FEDRAMP", name="FedRAMP — US Government Cloud", body="US GSA / FedRAMP PMO", domain="saas",
   region="US", jurisdictions=["United States"], category="cybersecurity",
   url="https://www.fedramp.gov/",
   summary="Standardised security assessment and authorisation for cloud products and services used by US federal agencies, built on NIST SP 800-53.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["us_gov"]),
   topics=["cloud","government","authorization"]),
 dict(id="DORA", name="EU DORA — Digital Operational Resilience", body="EU (ESAs)", domain="saas",
   region="EU", jurisdictions=["EU"], category="cybersecurity",
   url="https://eur-lex.europa.eu/eli/reg/2022/2554/oj",
   summary="ICT risk-management, incident reporting, resilience testing and third-party (incl. cloud) oversight requirements for EU financial entities and their critical ICT providers.",
   emerging=True, applies_when=dict(markets=["EU"], product_types=["fintech"]),
   topics=["resilience","ict risk","third-party"]),
 dict(id="PSD2", name="EU PSD2 — Payment Services", body="EU (EBA)", domain="saas",
   region="EU", jurisdictions=["EU"], category="payments",
   url="https://eur-lex.europa.eu/eli/dir/2015/2366/oj",
   summary="Rules for payment service providers including strong customer authentication (SCA) and secure open-banking access.",
   emerging=False, applies_when=dict(markets=["EU"], data_types=["payment"]),
   topics=["payments","sca","open banking"]),
 dict(id="GLBA", name="US GLBA — Financial Privacy & Safeguards", body="US FTC", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://www.ftc.gov/business-guidance/privacy-security/gramm-leach-bliley-act",
   summary="Requires financial institutions to protect customer financial information (Safeguards Rule) and explain information-sharing practices (Privacy Rule).",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["fintech"]),
   topics=["financial privacy","safeguards"]),
 dict(id="SOX", name="US SOX — Sarbanes-Oxley (IT Controls)", body="US SEC / PCAOB", domain="saas",
   region="US", jurisdictions=["United States"], category="assurance",
   url="https://www.sec.gov/",
   summary="Public-company financial-reporting accountability; Section 404 requires effective internal controls, including IT general controls over financial systems.",
   emerging=False, applies_when=dict(markets=["United States"], flags=["public_company"]),
   topics=["financial reporting","itgc","section 404"]),
 dict(id="COPPA", name="US COPPA — Children's Online Privacy", body="US FTC", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa",
   summary="Requires verifiable parental consent and data-handling limits for online services directed to, or knowingly collecting data from, children under 13.",
   emerging=False, applies_when=dict(markets=["United States"], data_types=["children"]),
   topics=["children","parental consent"]),
 dict(id="FERPA", name="US FERPA — Student Education Records", body="US Dept of Education", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://studentprivacy.ed.gov/ferpa",
   summary="Protects the privacy of student education records; EdTech vendors typically act as a 'school official' under strict use and disclosure limits.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["edtech"]),
   topics=["education","student records"]),
 dict(id="TCPA", name="US TCPA — Telemarketing & Messaging Consent", body="US FCC", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://www.fcc.gov/general/telemarketing-and-robocalls",
   summary="Consent and opt-out rules for automated calls, texts and faxes - relevant to product notifications and marketing messaging.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["saas","consumer","fintech"]),
   topics=["messaging","consent","marketing"]),
 dict(id="CAN-SPAM", name="US CAN-SPAM — Commercial Email", body="US FTC", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business",
   summary="Requirements for commercial email: accurate headers, clear identification, a physical address and a working unsubscribe mechanism.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["saas","consumer","fintech","edtech"]),
   topics=["email","marketing","unsubscribe"]),
 dict(id="EU-EPRIVACY", name="EU ePrivacy Directive (Cookies)", body="EU", domain="privacy",
   region="EU", jurisdictions=["EU"], category="privacy",
   url="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32002L0058",
   summary="Consent and transparency rules for cookies, tracking technologies and electronic communications, working alongside the GDPR.",
   emerging=False, applies_when=dict(markets=["EU"], data_types=["pii","eu_personal"]),
   topics=["cookies","tracking","consent"]),
 dict(id="EAA", name="EU European Accessibility Act (EN 301 549)", body="EU", domain="saas",
   region="EU", jurisdictions=["EU"], category="accessibility",
   url="https://ec.europa.eu/social/main.jsp?catId=1202",
   summary="Requires many digital products and services sold in the EU to meet accessibility requirements (aligned with EN 301 549 / WCAG).",
   emerging=True, applies_when=dict(markets=["EU"], product_types=["saas","consumer","fintech","edtech","healthcare_saas"]),
   topics=["accessibility","wcag","en 301 549"]),
 dict(id="ADA-WCAG", name="US ADA Web Accessibility (WCAG)", body="US DOJ", domain="saas",
   region="US", jurisdictions=["United States"], category="accessibility",
   url="https://www.ada.gov/resources/web-guidance/",
   summary="US guidance treating web and app accessibility (commonly WCAG conformance) as an ADA obligation for covered entities.",
   emerging=False, applies_when=dict(markets=["United States"], product_types=["saas","consumer","fintech","edtech","healthcare_saas"]),
   topics=["accessibility","ada","wcag"]),
 dict(id="US-STATE-PRIV", name="US State Privacy Laws (CPRA, VCDPA, CPA, …)", body="US States", domain="privacy",
   region="US", jurisdictions=["United States"], category="privacy",
   url="https://iapp.org/resources/article/us-state-privacy-legislation-tracker/",
   summary="A growing patchwork of comprehensive state consumer-privacy laws (California, Virginia, Colorado, Connecticut, Texas, Oregon and more) with rights, opt-outs and assessments.",
   emerging=True, applies_when=dict(markets=["United States"], data_types=["pii"]),
   topics=["privacy","state laws","opt-out"]),
 dict(id="ISO-22301", name="ISO 22301 — Business Continuity", body="ISO", domain="saas",
   region="Global", jurisdictions=["Global"], category="resilience",
   url="https://www.iso.org/standard/75106.html",
   summary="Management-system standard for business continuity - planning, exercising and recovering critical services after disruption.",
   emerging=False, applies_when=dict(product_types=["saas","fintech","edtech","healthcare_saas"]),
   topics=["continuity","resilience","recovery"]),
 dict(id="CSA-STAR", name="CSA STAR — Cloud Security Assurance", body="Cloud Security Alliance", domain="saas",
   region="Global", jurisdictions=["Global"], category="assurance",
   url="https://cloudsecurityalliance.org/star",
   summary="Cloud-specific security assurance program (CCM-based self-assessment or third-party certification) widely requested in SaaS vendor due diligence.",
   emerging=False, applies_when=dict(product_types=["saas","fintech","edtech","healthcare_saas"]),
   topics=["cloud","assurance","ccm"]),
 dict(id="ISO-20000", name="ISO/IEC 20000-1 — IT Service Management", body="ISO/IEC", domain="saas",
   region="Global", jurisdictions=["Global"], category="service-management",
   url="https://www.iso.org/standard/70636.html",
   summary="Requirements for an IT service management system - service levels, incident/change/problem management and continual improvement.",
   emerging=False, applies_when=dict(product_types=["saas","fintech","edtech","healthcare_saas"]),
   topics=["itsm","service levels"]),
]

# add source hashes (simulate stored snapshots so delta has a baseline)
for r in REGS:
    seed_text = f"{r['name']} | {r['summary']}"
    r["source_hash"] = hashlib.sha256(seed_text.encode()).hexdigest()
    r["version"] = "seed-1"

# ==========================================================================
# ENRICHMENT: give every regulation a fuller briefing -
#   what_it_is, why_important, detail, change, change_date, change_impact (+level)
# Curated specifics for high-value items; substantive templated text for the rest.
# All content is a model-assisted starting point and must be validated against
# the official source linked on each regulation.
# ==========================================================================
import datetime as _dt
_today = _dt.date.today()

# regulations with a real, specific recent change (what changed + when + impact)
CHANGES = {
 "FDA-CYBER": ("Final 524B cybersecurity guidance broadened SBOM expectations to transitive dependencies and set explicit post-market vulnerability-response timelines.", 14, "high",
   "Manufacturers of 'cyber devices' must deepen their SBOM and stand up a documented coordinated-disclosure and patching process before submission."),
 "HIPAA": ("A 2025 Notice of Proposed Rulemaking would make several historically 'addressable' Security Rule safeguards mandatory (encryption, MFA, asset inventory) and require annual risk-analysis updates.", 5, "high",
   "Re-grade every addressable safeguard as required and budget for encryption, MFA and continuous asset inventory."),
 "EU-AI-ACT": ("High-risk obligations are phasing in (2025-2027) and draft harmonised standards have been published, clarifying conformity expectations.", 9, "high",
   "Begin AI risk-management, data-governance, logging and human-oversight documentation now to be ready before the high-risk deadlines."),
 "EU-CRA": ("Secure-by-design and vulnerability-handling duties are confirmed, with reporting of actively-exploited vulnerabilities applying ahead of the 2027 main obligations.", 12, "high",
   "Connected products need a vulnerability-handling process, SBOM and an EU reporting path well before 2027."),
 "EU-NIS2": ("Member-state transposition is advancing, sharpening who counts as an essential/important entity and the applicable incident-reporting clocks.", 16, "high",
   "Confirm your entity classification and build 24h/72h incident-reporting workflows with management accountability."),
 "EU-GDPR": ("New EDPB guidance tightened expectations on processor due diligence and international-transfer documentation (SCC transfer impact assessments).", 7, "high",
   "Refresh DPAs, sub-processor due diligence and transfer impact assessments for all cross-border flows."),
 "UK-MDR": ("MHRA post-market surveillance regulations took effect, introducing new statutory PMS obligations for GB-marketed devices.", 11, "medium",
   "Stand up or update a GB-specific post-market surveillance and reporting process."),
 "MDCG-CYBER": ("Guidance was aligned more closely with FDA 524B expectations for security risk management evidence in MDR/IVDR technical documentation.", 18, "medium",
   "Ensure the technical file's security risk management matches the latest MDCG and FDA expectations."),
 "PCI-DSS": ("v4.0 future-dated requirements became mandatory in 2025 (MFA for all access, targeted risk analyses, stronger authentication).", 20, "medium",
   "If you touch card data, close the v4.0 future-dated items now - especially MFA everywhere and targeted risk analyses."),
 "FDA-PCCP": ("Final guidance lets manufacturers pre-authorise a Predetermined Change Control Plan for AI/ML model updates without a new submission each time.", 8, "high",
   "AI/ML device makers can define a PCCP to ship model updates faster - draft one as part of the submission."),
 "CMMC": ("The CMMC 2.0 program rule is being finalised and phased into US defense contracts, formalising third-party assessment tiers.", 22, "medium",
   "Defense-supply-chain vendors should map to NIST 800-171 and plan for the required assessment level."),
 "CN-PIPL": ("Clarified cross-border data-transfer mechanisms and security-assessment thresholds continue to tighten for personal information leaving China.", 15, "high",
   "Re-examine any China personal-data export against the latest transfer and localisation rules."),
 "EU-MDR": ("Transitional extension timelines remain in force, easing certificate deadlines but not the underlying requirements.", 21, "low",
   "Use the extension window to complete technical documentation and Notified Body work - obligations are unchanged."),
 "DORA": ("DORA's ICT risk-management, incident-reporting, resilience-testing and third-party oversight obligations became applicable in January 2025 for EU financial entities and their critical ICT providers.", 17, "high",
   "Fintech and their cloud/ICT providers must operationalise ICT risk management, incident reporting and resilience testing now."),
 "EAA": ("European Accessibility Act requirements apply from mid-2025 for many digital products and services placed on the EU market.", 13, "medium",
   "Set a WCAG/EN 301 549 conformance target and remediate accessibility gaps before EU launch."),
 "US-STATE-PRIV": ("Multiple new US state privacy laws took effect in 2024-2025 (Virginia, Colorado, Connecticut, Texas, Oregon and more), expanding consumer rights and opt-out duties.", 10, "medium",
   "Build a multi-state privacy program: rights handling, opt-outs (incl. Global Privacy Control) and data-protection assessments."),
 "FEDRAMP": ("FedRAMP modernisation is streamlining authorisation and pushing automation ('20x'), changing how cloud vendors pursue federal authorisation.", 19, "medium",
   "Cloud vendors targeting US government should plan the authorisation path and NIST 800-53 control implementation early."),
}

# domain-level statements used to compose why_important / detail for all regs
_DWHY = {
 "device": "it determines whether a medical device can legally and safely reach and stay on the market",
 "privacy": "it dictates how personal and health data must be protected, backed by regulator enforcement and significant penalties",
 "itot": "it sets the cybersecurity and resilience bar that protects connected systems and the data they carry",
 "ai": "it governs how AI must be built and operated to remain safe, transparent and accountable",
 "manufacturing": "it governs the quality, safety and environmental integrity of how products are made",
}
_CATPHRASE = {
 "premarket": "a market-authorisation requirement", "qms": "a quality-management-system requirement",
 "cybersecurity": "a cybersecurity requirement", "privacy": "a data-protection requirement",
 "risk": "a risk-management requirement", "software": "a software-lifecycle requirement",
 "safety": "a product-safety requirement", "labelling": "a labelling/identification requirement",
 "ai": "an AI-governance requirement", "assurance": "an independent-assurance requirement",
 "payments": "a payment-data-security requirement", "records": "an electronic-records-integrity requirement",
 "interoperability": "a data-interoperability requirement", "environment": "an environmental-management requirement",
}

def _scope_phrase(aw):
    parts = []
    L = {"phi": "US health data (PHI)", "eu_personal": "EU personal/health data", "pii": "personal data",
         "payment": "payment data", "software": "software-based products", "connected": "network-connected products",
         "ai": "AI/ML-enabled products", "ot": "operational-technology / ICS", "manufactures": "manufactured products",
         "samd": "software-as-a-medical-device", "medical_device": "medical devices", "ivd": "in-vitro diagnostics",
         "healthcare_saas": "healthcare SaaS"}
    if aw.get("markets"): parts.append("organisations operating in " + ", ".join(aw["markets"]))
    if aw.get("product_types"): parts.append("makers of " + ", ".join(L.get(x, x) for x in aw["product_types"]))
    if aw.get("data_types"): parts.append("anyone processing " + ", ".join(L.get(x, x) for x in aw["data_types"]))
    if aw.get("flags"): parts.append("products that are " + ", ".join(L.get(x, x) for x in aw["flags"]))
    return "; and ".join(parts) if parts else "a broad range of organisations"

for r in REGS:
    aw = r.get("applies_when", {})
    catp = _CATPHRASE.get(r["category"], "a regulatory requirement")
    dwhy = _DWHY.get(r["domain"], "it sets requirements organisations must meet")
    # what it is
    r["what_it_is"] = r["summary"]
    # why it is important
    maturity = ("Because it is still emerging, acting early avoids costly retrofits and submission delays."
                if r.get("emerging") else
                "It is well established and is routinely examined in audits, certifications and market reviews.")
    r["why_important"] = (f"Issued by {r['body']} for {', '.join(r['jurisdictions'])}, this is {catp}, and "
                          f"it matters because {dwhy}. {maturity}")
    # detailed description
    topics = ", ".join(r.get("topics", [])) or r["category"]
    r["detail"] = (f"{r['summary']} It applies to {_scope_phrase(aw)}. "
                   f"Within the {r['domain']} domain it is categorised as {r['category']}, and its core themes include {topics}. "
                   f"Compliance is typically demonstrated through documentation, testing and evidence that {r['body']} or an "
                   f"assessor can review; gaps can delay market access, fail an audit, or trigger enforcement. "
                   f"Always confirm the current text and obligations against the official source linked below.")
    # what changed, when, impact
    if r["id"] in CHANGES:
        msg, days_ago, lvl, note = CHANGES[r["id"]]
        r["change"] = "new" if r.get("emerging") and r["id"] in ("EU-AI-ACT", "EU-CRA", "FDA-PCCP") else "updated"
        r["change_date"] = (_today - _dt.timedelta(days=days_ago)).isoformat()
        r["change_impact"] = lvl
        r["change_note"] = note
        r["delta"] = msg
    else:
        r["change"] = "unchanged"
        r["change_date"] = (_today - _dt.timedelta(days=(hash(r["id"]) % 25) + 5)).isoformat()
        r["change_impact"] = "low"
        r["change_note"] = "No action required from this cycle; continue monitoring the official source for updates."
        r["delta"] = "No material change detected in the current cycle."
    # headline impact level for the card/feed
    r["impact"] = r["change_impact"] if r["change"] != "unchanged" else (
        "high" if r["domain"] in ("privacy", "ai") or r["category"] == "cybersecurity" else
        "medium" if r["category"] in ("qms", "premarket", "payments", "records") else "low")


# --------------------------------------------------------------------------
# CONTROLS  (practical, actionable; mapped to regulation ids)
# Each: id, domain, title, explanation, actions[], priority, severity_score,
#       phase(1-5), effort(S/M/L), regulations[]
# --------------------------------------------------------------------------
P_SCORE = {"Critical": 9.0, "High": 7.0, "Medium": 5.0, "Low": 2.5}
def sev(p): return {"Critical":"Critical","High":"High","Medium":"Moderate","Low":"Low"}[p]

def C(id, domain, title, why, actions, prio, phase, effort, regs):
    return dict(id=id, domain=domain, title=title, explanation=why, actions=actions,
                priority=prio, severity=sev(prio), score=P_SCORE[prio], phase=phase,
                effort=effort, regulations=regs)

CONTROLS = [
 # Governance / QMS
 C("GOV-01","Governance","Appoint accountable owners (security, quality, privacy)",
   "Regulators and auditors expect named, accountable owners before any technical control is credited.",
   ["Designate a security officer, a management representative for the QMS, and a data-protection lead.",
    "Document responsibilities, escalation paths and management-review cadence.",
    "Record executive sign-off and review at least annually."],
   "Critical",1,"S",["ISO-13485","FDA-QMSR","HIPAA","ISO-27001","EU-NIS2","ISO-9001"]),
 C("GOV-02","Governance","Establish a quality management system (QMS)",
   "A QMS with design controls, CAPA and document control is a precondition for nearly every device market.",
   ["Implement ISO 13485 (and QMSR-aligned) procedures: design controls, CAPA, complaints, document control.",
    "Run internal audits and management reviews on a defined schedule.",
    "Maintain the Device Master Record and Design History File."],
   "Critical",1,"L",["ISO-13485","FDA-QMSR","MDSAP","ISO-9001"]),
 C("GOV-03","Governance","Maintain a unified control catalogue (crosswalk)",
   "One control set mapped to many regimes lets you implement and evidence once, then comply many.",
   ["Adopt a common control catalogue and map each control to applicable regulations.",
    "Maintain the crosswalk and review when regulations change.",
    "Operate a test-once/comply-many evidence model."],
   "High",1,"M",["ISO-27001","NIST-CSF","SOC2","HIPAA","EU-GDPR"]),
 # Risk
 C("RISK-01","Risk","Conduct lifecycle risk management (ISO 14971)",
   "Risk analysis, control and residual-risk acceptance are mandatory before market placement and recurring thereafter.",
   ["Define a risk management plan and hazard analysis (FMEA/FTA).",
    "Implement and verify risk controls; evaluate residual risk vs benefit.",
    "Feed post-market data back into the risk file."],
   "Critical",1,"M",["ISO-14971","EU-MDR","FDA-QMSR","IEC-60601"]),
 C("RISK-02","Risk","Security risk assessment (data + cyber)",
   "Security risk analysis is explicitly required (HIPAA, GDPR Art 35, IEC 62443, MDCG 2019-16) and drives prioritisation.",
   ["Inventory data flows and assets; identify threats and vulnerabilities.",
    "Score likelihood and impact; record in a risk register.",
    "Define a remediation roadmap with owners and dates."],
   "Critical",1,"M",["HIPAA","EU-GDPR","ISO-27001","MDCG-CYBER","IEC-62443","NIST-80082"]),
 # Software lifecycle
 C("SW-01","Software","Software lifecycle process (IEC 62304)",
   "A defined software lifecycle with classification and verification is referenced by FDA and EU MDR submissions.",
   ["Classify software (Class A/B/C) and document the development plan.",
    "Maintain requirements, architecture, unit/integration/system test records.",
    "Track SOUP/third-party components with versions."],
   "High",2,"L",["IEC-62304","EU-MDR","FDA-510K","FDA-QMSR"]),
 C("SW-02","Software","Generate and maintain an SBOM",
   "An SBOM is now mandatory for US cyber devices (524B) and expected under the EU CRA and MDCG guidance.",
   ["Produce an SBOM (CycloneDX or SPDX) in the build pipeline.",
    "Monitor components for new vulnerabilities continuously.",
    "Publish/share the SBOM as required by each market."],
   "Critical",2,"M",["FDA-CYBER","EU-CRA","MDCG-CYBER","IMDRF-CYBER"]),
 C("SW-03","Software","Secure development lifecycle & code scanning",
   "Secure-by-design and SAST/DAST/SCA gates satisfy CRA, 62443 SDL and SOC 2 change management.",
   ["Add SAST, DAST and dependency (SCA) scanning to CI/CD.",
    "Enforce code review and secrets scanning on the main branch.",
    "Gate releases on security findings."],
   "High",2,"M",["EU-CRA","IEC-62443","SOC2","ISO-27001"]),
 # Cyber / IAM / data
 C("CYB-01","Cyber","Coordinated vulnerability disclosure (CVD)",
   "A published CVD policy and response process is a minimum artefact for FDA 524B, CRA and NIS2.",
   ["Publish a vulnerability disclosure policy and intake channel.",
    "Define triage, remediation SLAs and advisories.",
    "Report actively-exploited vulnerabilities where required (CRA/NIS2)."],
   "Critical",3,"M",["FDA-CYBER","EU-CRA","EU-NIS2","IMDRF-CYBER"]),
 C("IAM-01","Cyber","Identity, MFA and least-privilege access",
   "Access control is the most-cited safeguard across frameworks and the leading breach root-cause.",
   ["Enforce SSO + MFA on all accounts; remove long-lived keys.",
    "Implement least-privilege RBAC and periodic access reviews.",
    "Log and retain access events."],
   "Critical",1,"M",["HIPAA","EU-GDPR","ISO-27001","SOC2","NIST-80053","PCI-DSS"]),
 C("DATA-01","Data","Encrypt data at rest and in transit",
   "Encryption/pseudonymisation satisfies HIPAA technical safeguards, GDPR Art 32 and PCI requirements.",
   ["Enable encryption for all stores and transport (TLS, KMS-managed keys).",
    "Manage keys with rotation and least-privilege access.",
    "Document the approach for audit."],
   "Critical",1,"M",["HIPAA","EU-GDPR","ISO-27001","PCI-DSS","NIST-80053"]),
 C("DATA-02","Data","Data classification, retention and deletion",
   "Knowing where regulated data lives and applying retention/deletion is foundational to privacy regimes.",
   ["Classify data and map flows (incl. special-category/health).",
    "Define retention schedules and secure deletion.",
    "Apply DLP and access monitoring on sensitive stores."],
   "High",2,"M",["EU-GDPR","HIPAA","ISO-27001"]),
 # Privacy specific
 C("PRIV-01","Privacy","Records of Processing & data-subject rights",
   "GDPR-specific obligations (RoPA, DSAR, DPIA) carry direct supervisory-authority enforcement.",
   ["Maintain Records of Processing Activities (Art 30).",
    "Operate a data-subject-rights workflow (access/erasure/portability).",
    "Run DPIAs for high-risk processing (Art 35)."],
   "High",2,"M",["EU-GDPR"]),
 C("PRIV-02","Privacy","Processor agreements (BAA / DPA)",
   "You are accountable for processors: HIPAA BAAs and GDPR Art 28 DPAs are mandatory and audited.",
   ["Execute BAAs (US/PHI) and DPAs (EU) with all processors.",
    "Maintain a sub-processor register and due-diligence records.",
    "Review vendors on a defined cycle."],
   "Critical",2,"M",["HIPAA","EU-GDPR","SOC2"]),
 # Monitoring / IR / resilience
 C("MON-01","Cyber","Centralised logging and monitoring",
   "Continuous monitoring and anomaly detection are required by SOC 2 CC7, HIPAA audit controls and NIS2.",
   ["Aggregate logs into a SIEM with anomaly alerting.",
    "Define alert triage SLAs and on-call.",
    "Retain logs per regulatory minimums."],
   "High",3,"M",["SOC2","HIPAA","EU-NIS2","ISO-27001","NIST-80082"]),
 C("IR-01","Cyber","Incident response & breach notification",
   "A tested IR capability with HIPAA 60-day, GDPR 72-hour and NIS2 reporting paths is mandatory.",
   ["Document an IR plan with a breach classification matrix.",
    "Build notification workflows (HIPAA 60-day, GDPR 72-hour, NIS2).",
    "Run an annual tabletop and keep regulator contacts ready."],
   "Critical",3,"M",["HIPAA","EU-GDPR","EU-NIS2","SOC2","FDA-CYBER"]),
 C("VULN-01","Cyber","Vulnerability & patch management",
   "Timely detection and patching is required by SOC 2 CC7.1, CRA and post-market cyber obligations.",
   ["Scan infrastructure and container images on a schedule.",
    "Set patch SLAs (e.g. critical 48h / high 14d).",
    "Track in ticketing and run periodic penetration tests."],
   "High",3,"M",["EU-CRA","FDA-CYBER","SOC2","ISO-27001","NIST-80082"]),
 C("BCP-01","Resilience","Backup, continuity and disaster recovery",
   "Availability and recoverability are HIPAA contingency, GDPR Art 32 resilience and SOC 2 Availability requirements.",
   ["Define RTO/RPO; automate and test backups (immutable where possible).",
    "Design multi-AZ/region and document a DR runbook.",
    "Run an annual DR test."],
   "High",3,"M",["HIPAA","EU-GDPR","SOC2","ISO-27001"]),
 # OT / ICS
 C("OT-01","OT","Segment OT/ICS networks (zones & conduits)",
   "IEC 62443 and NIST 800-82 require segmentation between IT and OT to limit blast radius.",
   ["Define zones and conduits; segment OT from IT and the internet.",
    "Apply least-privilege firewalling and unidirectional gateways where needed.",
    "Inventory OT assets and protocols."],
   "Critical",2,"L",["IEC-62443","NIST-80082","EU-NIS2"]),
 C("OT-02","OT","OT monitoring and secure remote access",
   "Continuous OT monitoring and brokered remote access reduce ICS compromise risk.",
   ["Deploy OT-aware monitoring/IDS.",
    "Broker and MFA all remote OT access.",
    "Patch OT with tested maintenance windows."],
   "High",3,"M",["IEC-62443","NIST-80082","EU-NIS2"]),
 # Manufacturing
 C("MFG-01","Manufacturing","Process & production controls",
   "Validated, controlled production processes are required by QMS and manufacturing standards.",
   ["Validate critical processes and maintain process controls.",
    "Implement traceability and nonconformance handling.",
    "Calibrate and maintain equipment on schedule."],
   "High",2,"M",["ISO-13485","FDA-QMSR","ISO-9001"]),
 C("MFG-02","Manufacturing","Worker safety & environmental controls",
   "OSHA, ISO 45001 and ISO 14001 require documented safety and environmental management on the shop floor.",
   ["Conduct hazard assessments; implement machine guarding and PPE.",
    "Maintain hazard communication and incident reporting.",
    "Track environmental aspects and compliance obligations."],
   "Medium",4,"M",["OSHA","ISO-45001","ISO-14001"]),
 # AI
 C("AI-01","AI","AI governance and data governance",
   "AI as a device safety component is high-risk under the EU AI Act; ISO 42001 and FDA expect lifecycle governance.",
   ["Inventory AI use; define an AI risk-management process.",
    "Govern training/validation/test datasets and document model cards.",
    "Implement human oversight and output audit trails."],
   "High",4,"M",["EU-AI-ACT","ISO-42001"]),
 C("AI-02","AI","AI security: no regulated data in prompts; testing",
   "Prevent leakage of PHI/personal data into models and test for prompt-injection.",
   ["Set a data-handling policy (no PHI/PII in prompts without controls).",
    "Test for prompt injection and unsafe outputs.",
    "Log model access and retain evidence."],
   "Medium",4,"S",["EU-AI-ACT","ISO-42001","HIPAA","EU-GDPR"]),
 # Labelling / records
 C("LBL-01","Labelling","Unique device identification (UDI)",
   "UDI labelling and database submission are required in the US (GUDID) and EU (EUDAMED).",
   ["Assign UDI-DI/UDI-PI and apply to labels.",
    "Submit to GUDID (US) and EUDAMED (EU).",
    "Keep UDI records current through changes."],
   "Medium",3,"S",["FDA-UDI","EU-MDR"]),
 C("REC-01","Records","Electronic records & audit trails (Part 11)",
   "Trustworthy e-records with audit trails and validation are required for FDA-regulated software.",
   ["Implement tamper-evident audit trails and access controls.",
    "Validate systems (IQ/OQ/PQ) and manage e-signatures.",
    "Retain records per requirements."],
   "Medium",3,"M",["FDA-21CFR11","FDA-QMSR"]),
 # Assurance / customer
 C("AUD-01","Assurance","SOC 2 Type II readiness",
   "Customers increasingly require a SOC 2 Type II report; it operationalises the Trust Services Criteria over a period.",
   ["Scope Trust Services Criteria and the observation period.",
    "Automate evidence collection and monitor operating effectiveness.",
    "Engage an independent auditor and prepare the system description."],
   "Medium",4,"M",["SOC2","ISO-27001"]),
 C("PMS-01","Post-market","Post-market surveillance & vigilance",
   "PMS, PMCF and adverse-event reporting are required by MDR, UK MDR and most device regimes.",
   ["Operate a PMS system and PMCF plan.",
    "Report incidents/vigilance to the relevant authority.",
    "Feed findings into risk and design updates."],
   "High",3,"M",["EU-MDR","UK-MDR","FDA-QMSR","TGA-AU","HC-CA"]),

 # --- additional controls (device, QMS, manufacturing, OT, AI, privacy) ---
 C("QMS-01","Governance","Design controls & Design History File",
   "Design inputs/outputs, verification, validation and a DHF are mandatory QMS evidence for device approval.",
   ["Define design inputs and trace to outputs and V&V.",
    "Hold and document design reviews at each stage.",
    "Maintain the Design History File and Device Master Record."],
   "Critical",1,"L",["ISO-13485","FDA-QMSR","EU-MDR","HC-CA"]),
 C("QMS-02","Governance","CAPA & complaint handling",
   "Corrective/preventive action and complaint handling are core QMS processes auditors always examine.",
   ["Operate a CAPA process with root-cause analysis and effectiveness checks.",
    "Log, triage and investigate complaints within defined timelines.",
    "Link complaints to vigilance and risk where applicable."],
   "High",2,"M",["ISO-13485","FDA-QMSR","MDSAP","ISO-9001"]),
 C("QMS-03","Governance","Document & record control",
   "Controlled documents and retained records underpin every QMS and electronic-records requirement.",
   ["Implement version-controlled SOPs with approval workflows.",
    "Define record retention and protect against loss/alteration.",
    "Control distribution and obsolescence of documents."],
   "Medium",2,"M",["ISO-13485","FDA-QMSR","FDA-21CFR11","ISO-9001"]),
 C("QMS-04","Governance","Internal audit & management review",
   "Scheduled internal audits and management reviews are explicit QMS clauses and MDSAP audit areas.",
   ["Run a risk-based internal audit programme.",
    "Hold management reviews covering quality objectives and metrics.",
    "Track findings to closure."],
   "Medium",3,"M",["ISO-13485","ISO-9001","ISO-27001","MDSAP"]),
 C("CLIN-01","Clinical","Clinical evaluation & evidence",
   "Clinical evaluation and (for high-risk) clinical investigation evidence are required by MDR/IVDR and FDA.",
   ["Plan and document a clinical evaluation per MEDDEV/MDR.",
    "Maintain a clinical evaluation report and update it from PMCF.",
    "Justify equivalence or generate clinical data as needed."],
   "High",3,"L",["EU-MDR","EU-IVDR","FDA-510K","PMDA-JP","NMPA-CN"]),
 C("LBL-02","Labelling","Labelling, IFU & EUDAMED/GUDID registration",
   "Compliant labelling, instructions-for-use and database registration are market-access prerequisites.",
   ["Produce labelling and IFU meeting each market's requirements.",
    "Register devices in GUDID (US) and EUDAMED (EU).",
    "Control label changes through the QMS."],
   "Medium",3,"M",["FDA-UDI","EU-MDR","EU-IVDR","UK-MDR","TGA-AU"]),
 C("SUP-01","Vendor","Supplier qualification & purchasing controls",
   "Qualified suppliers and purchasing controls are required by device QMS and manufacturing standards.",
   ["Qualify and risk-tier suppliers; keep an approved supplier list.",
    "Define purchasing controls and incoming inspection.",
    "Monitor supplier performance and re-evaluate periodically."],
   "Medium",2,"M",["ISO-13485","FDA-QMSR","ISO-9001","MDSAP"]),
 C("PROC-01","Manufacturing","Process validation & sterilization",
   "Validated processes (incl. sterilization where relevant) are mandatory where output cannot be fully verified.",
   ["Validate special processes (IQ/OQ/PQ); revalidate on change.",
    "Validate sterilization and packaging where applicable.",
    "Maintain process monitoring and statistical controls."],
   "High",3,"L",["ISO-13485","FDA-QMSR","ISO-9001"]),
 C("TRACE-01","Manufacturing","Traceability, lot control & recall readiness",
   "Lot traceability and a field-safety/recall process are required for timely corrective actions in the field.",
   ["Implement lot/serial traceability through production and distribution.",
    "Define a recall / field safety corrective action procedure.",
    "Test recall effectiveness periodically."],
   "Medium",3,"M",["ISO-13485","FDA-QMSR","EU-MDR","UK-MDR"]),
 C("HF-01","Usability","Human factors & usability engineering",
   "Use-related risk must be controlled via usability engineering (IEC 62366) and is reviewed by FDA and Notified Bodies.",
   ["Conduct formative and summative usability evaluations.",
    "Identify use errors and mitigate via design.",
    "Document the usability engineering file."],
   "Medium",3,"M",["IEC-62366","EU-MDR","FDA-510K"]),
 C("SAFE-01","Safety","Electrical safety, EMC & essential performance",
   "Type-testing to IEC 60601 (safety, EMC, essential performance) is required for medical electrical equipment.",
   ["Plan and conduct IEC 60601 type testing.",
    "Address EMC and environmental collateral standards.",
    "Maintain test reports in the technical file."],
   "Medium",3,"L",["IEC-60601","EU-MDR","FDA-510K"]),
 C("CYB-02","Cyber","Secure boot, firmware integrity & cryptography",
   "Device integrity (secure boot, signed firmware, strong crypto) is central to FDA 524B, CRA and IEC 62443.",
   ["Implement secure boot and signed firmware updates.",
    "Use vetted cryptography and managed keys/certificates.",
    "Protect debug/maintenance interfaces."],
   "High",2,"M",["FDA-CYBER","EU-CRA","IEC-62443","MDCG-CYBER","IMDRF-CYBER"]),
 C("OT-03","OT","OT asset inventory & vulnerability management",
   "An accurate OT asset inventory and tailored patching are foundational to NIST 800-82 and IEC 62443.",
   ["Maintain a live OT/ICS asset and software inventory.",
    "Assess vulnerabilities with OT-safe methods.",
    "Patch within tested maintenance windows; compensate where patching is infeasible."],
   "High",3,"M",["IEC-62443","NIST-80082","EU-NIS2"]),
 C("AI-03","AI","AI model validation, bias & performance monitoring",
   "High-risk AI requires validated performance, bias evaluation and ongoing monitoring under the EU AI Act and FDA guidance.",
   ["Validate model performance on representative data; evaluate bias.",
    "Document intended use, limits and a model card.",
    "Monitor live performance and drift; define update governance."],
   "High",4,"M",["EU-AI-ACT","ISO-42001"]),
 C("TRN-01","Governance","Security, privacy & quality training",
   "Workforce training and awareness are explicit requirements across HIPAA, GDPR, ISO 27001 and device QMS.",
   ["Deliver role-based security, privacy and GxP/QMS training.",
    "Track completion and competency.",
    "Refresh training on policy or regulatory change."],
   "Medium",2,"S",["HIPAA","EU-GDPR","ISO-27001","ISO-13485","SOC2"]),
 C("TRANS-01","Privacy","International data transfers & residency",
   "Cross-border transfer mechanisms (SCCs, adequacy) and residency controls are required for EU personal data.",
   ["Map cross-border data flows and apply transfer mechanisms (SCCs/adequacy).",
    "Complete transfer impact assessments where needed.",
    "Apply data-residency controls where required by market."],
   "High",3,"M",["EU-GDPR"]),
 # --- SaaS / cloud specific ---
 C("SAAS-01","Cyber","Multi-tenant isolation & data segregation",
   "SaaS platforms must guarantee that one customer (tenant) cannot access another's data; isolation is a top concern in security reviews, SOC 2 and FedRAMP.",
   ["Enforce tenant isolation at the data, application and network layers.",
    "Scope every query and authorization check to the tenant; test for cross-tenant access.",
    "Segregate or encrypt tenant data with per-tenant keys where feasible."],
   "Critical",2,"M",["SOC2","FEDRAMP","ISO-27017","CSA-STAR","HIPAA","ISO-27001"]),
 C("ACC-01","Usability","Accessibility conformance (WCAG / EN 301 549)",
   "Digital products increasingly must meet accessibility standards; the EU Accessibility Act and US ADA web guidance make WCAG conformance a legal expectation.",
   ["Adopt a WCAG 2.1/2.2 AA conformance target across the product.",
    "Test with assistive technologies and automated + manual audits.",
    "Publish an accessibility statement and remediate findings on a schedule."],
   "Medium",4,"M",["EAA","ADA-WCAG"]),

 # --- CMMC / NIST 800-171 (US defense supply chain) ---
 C("CUI-01","Defense","Scope CUI and define the assessment boundary",
   "CMMC and NIST 800-171 only credit controls inside a correctly drawn CUI boundary; a vague scope is the most common assessment failure.",
   ["Identify every system, person and flow that stores, processes or transmits CUI.",
    "Draw and diagram the assessment boundary (CUI enclave) and isolate it from the rest of the network.",
    "Document the System Security Plan (SSP) describing the boundary and how each control is met."],
   "Critical",1,"M",["CMMC","NIST-80171"]),
 C("CUI-02","Defense","FIPS-validated cryptography for CUI",
   "NIST 800-171 (3.13.11) and CMMC require FIPS 140-validated modules to protect CUI - ordinary TLS is not sufficient evidence on its own.",
   ["Use FIPS 140-2/3 validated cryptographic modules for CUI at rest and in transit.",
    "Record the CMVP certificate numbers for each module in the SSP.",
    "Disable non-validated cipher suites and legacy protocols."],
   "High",2,"M",["CMMC","NIST-80171"]),
 C("CUI-03","Defense","SPRS score, POA&M and assessment readiness",
   "DoD contracts require a current self-assessment score in SPRS and a managed POA&M; CMMC Level 2 adds a third-party (C3PAO) assessment.",
   ["Run the NIST 800-171 self-assessment and post the score to SPRS.",
    "Maintain a Plan of Action & Milestones (POA&M) for any unmet controls with owners and dates.",
    "Prepare evidence and schedule the required C3PAO assessment for the contract's CMMC level."],
   "High",3,"M",["CMMC","NIST-80171"]),
 C("CUI-04","Defense","Defense incident reporting & media protection",
   "DFARS requires reporting cyber incidents affecting CUI to DoD within 72 hours; media handling and sanitisation are explicit 800-171 control families.",
   ["Build a 72-hour DoD/DC3 incident-reporting workflow for incidents touching CUI.",
    "Mark, store and transport CUI media under the media-protection controls; sanitise before reuse or disposal.",
    "Preserve and protect incident images and malware artefacts as required by DFARS."],
   "High",3,"M",["CMMC","NIST-80171"]),

 # --- PCI DSS v4.0.1 (payment card data) ---
 C("PCI-01","Payments","Scope and segment the cardholder data environment (CDE)",
   "PCI DSS applies to everything in or connected to the CDE; network segmentation is the single biggest lever for reducing scope, cost and risk.",
   ["Map all cardholder data flows, storage and processing to define the CDE.",
    "Segment the CDE from the rest of the network and validate segmentation at least annually (six-monthly for service providers).",
    "Minimise stored cardholder data and never store sensitive authentication data after authorisation."],
   "Critical",2,"M",["PCI-DSS","PSD2"]),
 C("PCI-02","Payments","External (ASV) scanning & penetration testing",
   "PCI DSS requires quarterly external vulnerability scans by an Approved Scanning Vendor and annual segmentation-aware penetration testing.",
   ["Run quarterly ASV scans and remediate to a passing scan.",
    "Perform internal and external penetration tests at least annually and after significant change.",
    "Test segmentation controls as part of the penetration test."],
   "High",3,"M",["PCI-DSS"]),
 C("PCI-03","Payments","Anti-malware, change-detection & secure payment pages",
   "PCI DSS v4.0 strengthened protection of payment pages (e.g. script and change-/tamper-detection) and requires anti-malware on at-risk systems.",
   ["Deploy and maintain anti-malware on systems commonly affected by malware.",
    "Manage and monitor all scripts on payment pages and detect unauthorised changes to page headers/content.",
    "Use change- and file-integrity monitoring to alert on unexpected modifications in the CDE."],
   "High",3,"M",["PCI-DSS"]),
 C("PCI-04","Payments","Targeted risk analyses & customised approach (v4.0.1)",
   "PCI DSS v4.0 lets entities tailor how some requirements are met via a documented targeted risk analysis - now a mandatory, future-dated activity.",
   ["Perform a documented targeted risk analysis for each requirement that allows one (e.g. frequency-based tasks).",
    "Document any customised-approach controls and the assurance evidence supporting them.",
    "Review and refresh targeted risk analyses at least every 12 months."],
   "Medium",4,"S",["PCI-DSS"]),
]

reg_ids = {r["id"] for r in REGS}
for c in CONTROLS:
    missing = [x for x in c["regulations"] if x not in reg_ids]
    assert not missing, f"control {c['id']} references unknown regs {missing}"

# ---- augment mappings so newly added regulations also surface roadmaps ----
# (extends existing controls with the new regs they clearly satisfy)
AUGMENT = {
 # privacy laws -> privacy/data/access/IR/training/transfer controls
 "PRIV-01": ["US-CCPA","CA-PIPEDA","BR-LGPD","CN-PIPL","JP-APPI","UK-GDPR","SG-PDPA","KR-PIPA","ISO-27701","ISO-27018"],
 "PRIV-02": ["UK-GDPR","ISO-27701"],
 "DATA-01": ["ISO-27017","ISO-27018","CN-DSL","HITRUST","NIST-80171"],
 "DATA-02": ["US-CCPA","CA-PIPEDA","BR-LGPD","CN-PIPL","JP-APPI","UK-GDPR","SG-PDPA","KR-PIPA","ISO-27701","ISO-27018","CN-DSL"],
 "IAM-01": ["NIST-80171","CMMC","HITRUST","ISO-27017","CN-CSL"],
 "IR-01": ["US-CCPA","CA-PIPEDA","BR-LGPD","UK-GDPR","SG-PDPA","KR-PIPA","CN-CSL"],
 "TRANS-01": ["UK-GDPR","CN-PIPL","CN-DSL","KR-PIPA","JP-APPI"],
 "TRN-01": ["UK-GDPR","HITRUST","ISO-27701"],
 "MON-01": ["CN-CSL","NIST-80171","HITRUST","ISO-27017"],
 "VULN-01": ["UL-2900","IEC-81001","AAMI-TIR57","NIST-80171"],
 "BCP-01": ["ISO-27017","HITRUST"],
 # secure development / SBOM / firmware -> security standards
 "SW-02": ["IEC-81001","UL-2900","AAMI-TIR57"],
 "SW-03": ["IEC-81001","UL-2900","NIST-80171"],
 "CYB-01": ["IEC-81001","AAMI-TIR57","UL-2900"],
 "CYB-02": ["IEC-81001","UL-2900","AAMI-TIR57"],
 "RISK-02": ["IEC-81001","AAMI-TIR57","ISO-80001","CN-CSL"],
 # device QMS / clinical / labelling / PMS -> new country approvals + standards
 "QMS-01": ["ANVISA-BR","MFDS-KR","CDSCO-IN","HSA-SG","SWISSMEDIC-CH","FDA-PMA","FDA-DENOVO"],
 "QMS-02": ["ANVISA-BR","MFDS-KR","CDSCO-IN","HSA-SG","SWISSMEDIC-CH"],
 "CLIN-01": ["FDA-PMA","FDA-DENOVO","ANVISA-BR","MFDS-KR","CDSCO-IN","SWISSMEDIC-CH"],
 "LBL-02": ["SWISSMEDIC-CH","ISO-15223","ANVISA-BR","HSA-SG"],
 "PMS-01": ["ANVISA-BR","MFDS-KR","HSA-SG","SWISSMEDIC-CH"],
 "MFG-01": ["ANVISA-BR","ISO-11135","ISO-10993"],
 "PROC-01": ["ISO-11135"],
 "SAFE-01": ["ISO-10993"],
 "RISK-01": ["ISO-80001","ISO-10993"],
 "SW-01": ["IEC-81001","FDA-DENOVO","FDA-PMA"],
 # AI controls -> AI regs
 "AI-01": ["FDA-PCCP","FDA-GMLP","NIST-AI-RMF","OECD-AI"],
 "AI-02": ["NIST-AI-RMF","OECD-AI","CN-PIPL"],
 "AI-03": ["FDA-PCCP","FDA-GMLP","NIST-AI-RMF","OECD-AI"],
 # OT controls -> OT regs
 "OT-01": ["NERC-CIP","IEC-61508"],
 "OT-02": ["NERC-CIP","IEC-61508"],
 "OT-03": ["NERC-CIP","IEC-61508"],
 # assurance / governance -> frameworks
 "AUD-01": ["HITRUST","ISO-27017","SOC2","SOC1","CSA-STAR","FEDRAMP","SOX","ISO-20000"],
 "GOV-03": ["NIST-80171","CMMC","HITRUST","ISO-27701","NIST-AI-RMF","SOX","DORA","ISO-20000"],
 "REC-01": ["US-CURES","SOC1","SOX","GLBA"],
}
# additional SaaS / cloud mappings (kept separate so they MERGE with the above
# instead of overwriting shared keys like PRIV-01 / DATA-02)
AUGMENT_SAAS = {
 "IAM-01": ["SOC2","FEDRAMP","CSA-STAR","PSD2","GLBA","DORA"],
 "DATA-01": ["SOC2","FEDRAMP","CSA-STAR","DORA","PSD2","GLBA"],
 "DATA-02": ["GLBA","COPPA","FERPA","EU-EPRIVACY","US-STATE-PRIV","SOC2"],
 "PRIV-01": ["GLBA","COPPA","FERPA","EU-EPRIVACY","US-STATE-PRIV"],
 "PRIV-02": ["EU-EPRIVACY","TCPA","CAN-SPAM","US-STATE-PRIV","COPPA"],
 "MON-01": ["SOC2","FEDRAMP","DORA","CSA-STAR","ISO-20000"],
 "VULN-01": ["FEDRAMP","DORA","CSA-STAR","SOC2"],
 "IR-01": ["DORA","FEDRAMP","SOC2","GLBA","US-STATE-PRIV"],
 "BCP-01": ["ISO-22301","DORA","SOC2","FEDRAMP","ISO-20000"],
 "SUP-01": ["DORA","SOC2","CSA-STAR"],
 "TRN-01": ["SOC2","GLBA","COPPA","FERPA","CAN-SPAM"],
 "TRANS-01": ["EU-EPRIVACY","US-STATE-PRIV"],
}
for _k, _v in AUGMENT_SAAS.items():
    AUGMENT.setdefault(_k, [])
    AUGMENT[_k] = list(dict.fromkeys(AUGMENT[_k] + _v))

# Cross-map foundational controls to CMMC (NIST 800-171 families) and PCI DSS
# so those two regimes get a complete roadmap, not just their dedicated controls.
AUGMENT_CMMC_PCI = {
    "GOV-01":  ["CMMC"],
    "RISK-02": ["CMMC", "PCI-DSS"],
    "SW-03":   ["PCI-DSS"],          # secure SDLC covers PCI Req 6
    "MON-01":  ["CMMC", "PCI-DSS"],  # logging: 800-171 AU / PCI Req 10
    "IR-01":   ["CMMC", "PCI-DSS"],  # incident response: PCI Req 12.10
    "VULN-01": ["CMMC", "PCI-DSS"],  # vuln/patch: PCI Req 6/11
    "BCP-01":  ["CMMC"],
    "TRN-01":  ["CMMC", "PCI-DSS"],  # security awareness training
    "DATA-02": ["PCI-DSS"],          # retention/disposal of card data
}
for _k, _v in AUGMENT_CMMC_PCI.items():
    AUGMENT.setdefault(_k, [])
    AUGMENT[_k] = list(dict.fromkeys(AUGMENT[_k] + _v))

ctrl_by_id = {c["id"]: c for c in CONTROLS}
for cid, extra in AUGMENT.items():
    if cid in ctrl_by_id:
        cur = ctrl_by_id[cid]["regulations"]
        for rid in extra:
            if rid in reg_ids and rid not in cur:
                cur.append(rid)

json.dump(REGS, open(os.path.join(OUT, "regulations.json"), "w"), indent=2)
json.dump(CONTROLS, open(os.path.join(OUT, "controls.json"), "w"), indent=2)
print(f"Wrote {len(REGS)} regulations and {len(CONTROLS)} controls to {OUT}")
